
export const FOOTERNAV_ITEMS = "NAV_ITEMS";

export const LCL_ACTIVE = "LCL_ACTIVE";
export const LCL_COMPLETE = "LCL_COMPLETE";

export const FCL_ACTIVE = "FCL_ACTIVE";
export const FCL_COMPLETE = "FCL_COMPLETE";

export const AIR_ACTIVE_SELECTED = "AIR_ACTIVE_SELECTED";
export const AIR_COMPLETE_SELECTED = "AIR_COMPLETE_SELECTED";

export const CARGO_ACTIVE_SELECTED = "CARGO_ACTIVE_SELECTED";

export const LCL_ACTIVE_SELECTED_NEW = "LCL_ACTIVE_SELECTED_NEW";
  
export const FETCH_USERS_SELECTED = 'FETCH_SELECTED_USER';


export const ITEMS_IS_LOADING = 'ITEMS_IS_LOADING';
export const ITEMS_HAS_ERRORED = 'ITEMS_HAS_ERRORED';
export const ITEMS_FETCH_DATA_SUCCESS = 'ITEMS_FETCH_DATA_SUCCESS';

